// SOURCE OF TRUTH — the 2026 draft, transcribed verbatim from the draft board.
// Each entry: [teamNameAsDrafted, "over" | "under", line]
// Do not reorder: array order is draft order within each player.

// `car` is the high school ride, self-hosted under public/cars/.
export const PLAYERS = [
  { id: 'karn', name: 'Karn', car: '/cars/karn.jpg', carName: 'Honda Prelude' },
  { id: 'steve', name: 'Steve', car: '/cars/steve.jpg', carName: 'Ford F-150' },
  { id: 'squeel', name: 'Squeel', car: '/cars/squeel.jpg', carName: 'Olds Cutlass Supreme' },
];

export const DRAFT = {
  karn: [
    ['Alabama', 'under', 8.5],
    ['Arkansas State', 'over', 5.5],
    ['Ball State', 'under', 3.5],
    ['Boston College', 'under', 3.5],
    ['BYU', 'over', 8.5],
    ['Cal', 'over', 6.5],
    ['Clemson', 'over', 7.5],
    ['CMU', 'over', 6.5],
    ['Colorado', 'under', 4.5],
    ['Florida', 'under', 7.5],
    ['Georgia State', 'under', 3.5],
    ['Hilltoppers', 'over', 6.5],
    ['Houston', 'under', 8.5],
    ['Illinois', 'under', 7.5],
    ['Iowa', 'over', 7.5],
    ['Kent State', 'under', 3.5],
    ['Kentucky', 'under', 4.5],
    ['La Tech', 'over', 5.5],
    ['Liberty', 'over', 6.5],
    ['LSU', 'under', 8.5],
    ['Maryland', 'over', 4.5],
    ['Miami FL', 'under', 10.5],
    ['Michigan', 'under', 8.5],
    ['Minnesota', 'over', 5.5],
    ['Missouri', 'over', 6.5],
    ['Missouri State', 'under', 4.5],
    ['Navy', 'over', 7.5],
    ['North Carolina', 'under', 4.5],
    ['Notre Dame', 'under', 11.5],
    ['Oklahoma', 'over', 7.5],
    ['Ole Miss', 'over', 7.5],
    ['Pittsburgh', 'under', 7.5],
    ['Rutgers', 'over', 4.5],
    ['Sam Houston', 'under', 3.5],
    ['SMU', 'over', 7.5],
    ['Texas', 'under', 9.5],
    ['Texas Tech', 'over', 10.5],
    ['Toledo', 'over', 7.5],
    ['Troy', 'under', 6.5],
    ['Tulane', 'over', 7.5],
    ['UTEP', 'under', 3.5],
    ['Vandy', 'over', 5.5],
    ['Washington State', 'over', 4.5],
    ['Wisconsin', 'under', 6.5],
  ],
  steve: [
    ['App State', 'over', 5.5],
    ['Arizona', 'under', 7.5],
    ['Arkansas', 'under', 4.5],
    ['Army', 'under', 7.5],
    ['Auburn', 'under', 6.5],
    ['Baylor', 'under', 6.5],
    ['Boise State', 'over', 7.5],
    ['Charlotte', 'over', 2.5],
    ['East Carolina', 'under', 7.5],
    ['Fresno State', 'under', 6.5],
    ['Georgia', 'over', 9.5],
    ['Hawaii', 'over', 7.5],
    ['James Madison', 'under', 9.5],
    ['Kansas', 'over', 5.5],
    ['Marshall', 'under', 7.5],
    ['Miami OH', 'under', 7.5],
    ['Michigan State', 'over', 4.5],
    ['NC State', 'over', 7.5],
    ['Nebraska', 'under', 6.5],
    ['Nevada', 'under', 4.5],
    ['New Mexico', 'over', 7.5],
    ['New Mexico State', 'under', 4.5],
    ['Northern Illinois', 'over', 3.5],
    ['Ohio State', 'over', 9.5],
    ['Oregon', 'over', 10.5],
    ['Oregon State', 'under', 3.5],
    ['Penn State', 'under', 8.5],
    ['Purdue', 'under', 3.5],
    ['SDSU', 'over', 6.5],
    ['South Carolina', 'under', 6.5],
    ['TCU', 'over', 6.5],
    ['Tennessee', 'over', 7.5],
    ['Texas State', 'over', 5.5],
    ['UAB', 'over', 3.5],
    ['UCLA', 'over', 6.5],
    ['UNLV', 'over', 7.5],
    ['USC', 'under', 8.5],
    ['Utah', 'under', 8.5],
    ['Utah State', 'under', 4.5],
    ['Virginia', 'under', 7.5],
    ['Virginia Tech', 'over', 6.5],
    ['Washington', 'over', 7.5],
    ['West Virginia', 'over', 5.5],
    ['Wyoming', 'over', 5.5],
  ],
  squeel: [
    ['Air Force', 'over', 6.5],
    ['Akron', 'over', 4.5],
    ['Arizona State', 'over', 6.5],
    ['Bowling Green', 'over', 4.5],
    ['Buffalo', 'under', 5.5],
    ['Cincinnati', 'under', 5.5],
    ['Coastal Carolina', 'under', 4.5],
    ['CSU', 'over', 3.5],
    ['Delaware', 'over', 5.5],
    ['Duke', 'under', 5.5],
    ['Eastern Michigan', 'over', 5.5],
    ['FAU', 'over', 5.5],
    ['FIU', 'over', 6.5],
    ['Florida State', 'under', 6.5],
    ['Georgia Tech', 'under', 6.5],
    ['Indiana', 'under', 10.5],
    ['Iowa State', 'under', 5.5],
    ['Jacksonville State', 'over', 7.5],
    ['Kansas State', 'under', 8.5],
    ['Kennesaw State', 'under', 6.5],
    ['Louisville', 'over', 7.5],
    ['Memphis', 'under', 7.5],
    ['Middle Tennessee', 'under', 3.5],
    ['Mississippi State', 'over', 4.5],
    ['NDSU', 'under', 8.5],
    ['North Texas', 'under', 9.5],
    ['Northwestern', 'under', 5.5],
    ['Old Dominion', 'over', 7.5],
    ['Rice', 'over', 3.5],
    ['Sac State', 'under', 4.5],
    ['San Jose', 'under', 5.5],
    ['South Florida', 'under', 8.5],
    ['Southern Miss', 'under', 4.5],
    ['Stanford', 'over', 3.5],
    ['Syracuse', 'under', 4.5],
    ['Temple', 'over', 5.5],
    ['Texas AM', 'under', 8.5],
    ['Tulsa', 'over', 5.5],
    ['UCF', 'over', 5.5],
    ['UConn', 'under', 6.5],
    ['ULM', 'over', 3.5],
    ['UMass', 'over', 3.5],
    ['UTSA', 'over', 7.5],
    ['Wake Forest', 'over', 5.5],
  ],
};

// Draft name -> ESPN `location` field. Only names that differ from ESPN's own
// spelling need an entry here; everything else matches exactly.
export const ALIASES = {
  Cal: 'California',
  CMU: 'Central Michigan',
  Hilltoppers: 'Western Kentucky',
  'La Tech': 'Louisiana Tech',
  'Miami FL': 'Miami',
  'Miami OH': 'Miami (OH)',
  Vandy: 'Vanderbilt',
  Hawaii: "Hawai'i",
  SDSU: 'San Diego State',
  CSU: 'Colorado State',
  NDSU: 'North Dakota State',
  'Sac State': 'Sacramento State',
  'San Jose': 'San José State',
  'Texas AM': 'Texas A&M',
  ULM: 'UL Monroe',
  UMass: 'Massachusetts',
  FIU: 'Florida International',
  FAU: 'Florida Atlantic',
};

// ESPN has duplicate `location` strings across divisions (e.g. two "Charlotte").
// Pin these to an exact ESPN team id to remove all doubt.
export const ID_OVERRIDES = {
  Charlotte: '2429', // Charlotte 49ers (FBS), not Charlotte College
  Delaware: '48', // Delaware Blue Hens, not Delaware State / Delaware Valley
  Troy: '2653', // Troy Trojans (FBS), not Troy Vikings (D-III)
};
